import {
  AlertTriangle,
  ArrowRight,
  Bell,
  Calendar,
  Camera,
  Car,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Clipboard,
  ClipboardCheck,
  Clock,
  Copy,
  CreditCard,
  Download,
  Edit3,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Image as ImageIcon,
  Info,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  MoreHorizontal,
  Phone,
  Plus,
  RefreshCw,
  Send,
  Settings,
  ShoppingBag,
  Sparkles,
  Star,
  Trash2,
  TrendingUp,
  User,
  Users,
  X,
  type LucideIcon,
} from 'lucide-react-native';

const REGISTRY = {
  alert: AlertTriangle,
  'arrow-right': ArrowRight,
  bell: Bell,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  copy: Copy,
  'credit-card': CreditCard,
  download: Download,
  edit: Edit3,
  eye: Eye,
  'eye-off': EyeOff,
  file: FileText,
  flame: Flame,
  gift: Gift,
  graduation: GraduationCap,
  heart: Heart,
  home: Home,
  image: ImageIcon,
  info: Info,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  pin: MapPin,
  message: MessageCircle,
  more: MoreHorizontal,
  phone: Phone,
  plus: Plus,
  refresh: RefreshCw,
  send: Send,
  settings: Settings,
  shop: ShoppingBag,
  sparkles: Sparkles,
  star: Star,
  trash: Trash2,
  trending: TrendingUp,
  user: User,
  users: Users,
  close: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof REGISTRY;

type Props = {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  fill?: string;
};

export function Icon({ name, size = 18, color = '#EEEEF0', strokeWidth = 1.8, fill }: Props) {
  const Cmp = REGISTRY[name];
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} fill={fill ?? 'none'} />;
}
